---
- name: use package module
  hosts: localhost
  gather_facts: yes
  vars:
    package_name: "{{ package }}"
  tasks:
     - name: Installs a package
       failed_when: (package is undefined) or (package|length == 0)       
       package:
          name: "{{ package }}"
          state: present
